version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./Backend/.base.env
    networks:
      - default

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "7072:7072"
    env_file:
      - ./Backend/.base.env     
    depends_on:
      - db
    networks:
      - default
      
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata:
